GET http://localhost:5000/
###

POST http://localhost:5000/
Content-Type: application/json

{
   "id": 6,
   "name": "sanit"
}
###

POST http://websocket-apis.herokuapp.com/
Content-Type: application/json

{
   "id": 6,
   "name": "sanit"
}